language: java
jdk: openjdk8
addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools
      - python3-wheel

before_script:
  # Use a newer version of Python
  - pyenv versions
  - pyenv global 3.6.7
  # Setup biotestmine to test against
  - pip3 install intermine-boot
  - intermine_boot start local --build-im --im-branch bluegenes
  # Install lein - required to build the project
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -O /tmp/lein
  - chmod +x /tmp/lein
  - export PATH=$PATH:/tmp/lein
  # make several attempts at downloading dependencies
  - travis_retry lein deps
  # check code is well formatted
  - lein cljfmt check

script:
  - lein doo phantom test once
  # build API docs
  - lein codox
  
# Deploys build API docs:
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: target/doc
  on:
    branch: dev
